// Minimal placeholder for Convex generated API surface.
// This file provides a small `api` object so imports elsewhere in the app compile.
// In a real Convex workflow this file is generated by `convex dev`.

// Minimal generated API shim for Convex server functions.
// Update this file by running `convex dev` in a real development workflow.
export const api: any = {
  products: {
    listAllProducts: { name: "products:listAllProducts" },
  },
  favorites: {},
  search: {
    getSearchPanelData: { name: "search:getSearchPanelData" },
    logSearch: { name: "search:logSearch" },
    listRecentSearches: { name: "search:listRecentSearches" },
    searchProducts: { name: "search:searchProducts" },
  },
  sessions: {},
  phoneActions: {
    createPhoneActionRequest: { name: "phoneActions:createPhoneActionRequest" },
    createExchangeRequestMiniapp: { name: "phoneActions:createExchangeRequestMiniapp" },
    listAllPhoneActions: { name: "phoneActions:listAllPhoneActions" },
    listAllExchangeRequests: { name: "phoneActions:listAllExchangeRequests" },
    updateExchangeStatus: { name: "phoneActions:updateExchangeStatus" },
    getExchangeRequestsV2: { name: "phoneActions:getExchangeRequestsV2" },
    getExchangeDetailV2: { name: "phoneActions:getExchangeDetailV2" },
  },
  affiliates: {},
  mutations: {
    sellers: {
      authenticateWithTelegram: {
        name: "mutations/sellers:authenticateWithTelegram",
      },
      createSession: { name: "mutations/sellers:createSession" },
      revokeSession: { name: "mutations/sellers:revokeSession" },
      createSeller: { name: "mutations/sellers:createSeller" },
    },
    products: {
      createProduct: { name: "mutations/products:createProduct" },
      updateProduct: { name: "mutations/products:updateProduct" },
      updateProductStatus: {
        name: "mutations/products:updateProductStatus",
      },
      deleteProduct: { name: "mutations/products:deleteProduct" },
      updateProductStock: { name: "mutations/products:updateProductStock" },
    },
    categories: {
      createCategory: { name: "mutations/categories:createCategory" },
      updateCategory: { name: "mutations/categories:updateCategory" },
      deleteCategory: { name: "mutations/categories:deleteCategory" },
      reorderCategories: { name: "mutations/categories:reorderCategories" },
    },
  },
};
